# Используем тот же базовый образ с зависимостями
FROM bot-dependencies:latest

LABEL maintainer="clegpscb@gmail.com"
LABEL description="Events sync cron service using pre‑installed dependencies"

WORKDIR /app

# Копируем код приложения
COPY . .



# Настраиваем PYTHONPATH
ENV PYTHONPATH=/dependencies/lib/python3.11/site-packages:$PYTHONPATH

# Запуск cron‑сервиса
CMD ["python", "get_all_main.py"]
