services:
  events-sync:
    build: 
      context: .
      dockerfile: Dockerfile.cron
    container_name: events-sync-cron
    dns:
      - 8.8.8.8      # Google DNS
      - 1.1.1.1   # Cloudflare DNS
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
      - USE_HTTPS=${USE_HTTPS}
      - CERT_PATH=${CERT_PATH}
      - KEY_PATH=${KEY_PATH}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - POSTGRES_URI=${POSTGRES_URI}
      - MODEL_NAME=${MODEL_NAME}
      - CACHE_TTL=${CACHE_TTL}
      - BATCH_SIZE=${BATCH_SIZE}
      - TOP_K=${TOP_K}
      - SIMILARITY_THRESHOLD=${SIMILARITY_THRESHOLD}
      - CLUSTERS_PATH=${CLUSTERS_PATH}
      - ADMIN_IDS=${ADMIN_IDS}
      - DELIMETER_PERCENT_ADDED=${DELIMETER_PERCENT_ADDED}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
  
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge