{{- if .Values.certManager.createClusterIssuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuerName }}
  labels:
    {{- include "vayobyzh.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ required "certManager.email is required" .Values.certManager.email | quote }}
    server: {{ .Values.certManager.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.certManager.issuerName }}-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: {{ .Values.ingress.className | quote }}
{{- end }}
